// const ACTION={
//     USER_LOGGED_IN:"USER_LOGGED_IN",
//     CLOUDINARY_IMAGE:"CLOUDINARY_IMAGE",
//     SEARCH_POST:"SEARCH_POST",
//     CHALLENGE_POST:"CHALLENGE_POST",
//     COMMUNITY_POST:"COMMUNITY_POST",
//     COMMUNITY:"COMMUNITY"
// }

// export default ACTION

export const SAVE_USER_DETAIL = "SAVE_USER_DETAIL";